### ISSUE TITLE
Support for `qs.parse` options

### ISSUE THREAD

**Issue by Ajaxy** [koajs/qs#18]
`qs.parse(..., options)` supports 2nd parameter `options`. It may be useful for example fo a custom `decoder` option. Here is the PR for it (including updating the `qs` version).

**Comment by hugoduraes** [comment]
This would a nice improvement to this package. Can anyone merge it? @fengmk2 @jonathanong @fl0w @ugin

**Comment by niftylettuce** [comment]
released to npm as v3.0.0

https://github.com/koajs/qs/releases/tag/v3.0.0
