### ISSUE TITLE
Is this library alive?

### ISSUE THREAD

**Issue by Ajaxy** [koajs/qs#20]
This one looks a bit stale. What's the best approach to use `koa` with `qs` now?

**Comment by jonathanong** [comment]
@Ajaxy i'll add you as a collaborator. i see `qs` as an anti-pattern

**Comment by Ajaxy** [comment]
@jonathanong Why?

**Comment by jonathanong** [comment]
qs has historically had many security issues. nowadays, just use JSON or GraphQL

**Comment by Ajaxy** [comment]
Using JSON would be bad for the readability of URL for GET requests. And things like [cast-with-schema](https://www.npmjs.com/package/cast-with-schema) help with security issues.

**Comment by niftylettuce** [comment]
Library is active, we are releasing new version soon thanks to @3imed-jaberi work.  PR #19 will be added too.
