### ISSUE TITLE
3.0.0 plan

### ISSUE THREAD

**Issue by fengmk2** [koajs/qs#5]
# request.query and request.queries

Make `request.query[key]` return strict `String` value and add `request.queries[key]` to return `Array` value.
- delegate `ctx.query` to `request.query`
- delegate `ctx.queries` to `request.queries`
## `request.query[key]`

return `String` value
- if key not exists, return `undefined`
- `foo[bar][baz]=foobarbaz` => `{ 'foo[bar][baz]': 'foobarbaz' }`
  - `request.query.foo` return `undefined` 
  - `request.query['foo[bar][baz]']` return `'foobarbaz'`
- `a[]=b&a[]=c` => `{ 'a[]': 'b' }`
  - `request.query.a` return `undefined` 
  - `request.query['a[]']` return `b`
- `a=b&a=c` => `{ 'a': 'b' }`
  - `request.query.a` return `b`
## `request.queries[key]`

return `Array` value
- if key not exists, return `undefined`
- `foo[bar][baz]=foobarbaz` => `{ 'foo[bar][baz]': [ 'foobarbaz' ] }`
  - `request.queries.foo` return `undefined`
  - `request.queries['foo[bar][baz]']` return `[ 'foobarbaz' ]`
- `a[]=b&a[]=c` => `{ 'a[]': [ 'b', 'c' ] }`
  - `request.queries.a` return `undefined`
  - `request.queries['a[]']` return `['b', 'c']`
- `a=b` => `{ 'a': [ 'b' ] }`
  - `request.queries.a` return `['b']`
- `a=b&a=c` => `{ 'a': [ 'b', 'c' ] }`
  - `request.queries.a` return `['b', 'c']`

**Comment by fengmk2** [comment]
I don't want to write codes like these any more.

```js
var val = this.query.foo;
if (Array.isArray(val)) {
  // ...
} else {
  // ...
}
```

**Comment by jonathanong** [comment]
What are you going to use as a query string parsing library? I think @dougwilson and i had plans for a new query string parser. 

I personally wish it was always a string. If you want types, you should be using JSON!

**Comment by fengmk2** [comment]
@jonathanong yep, I personally only using string value. But other user want more value type, and I want to help them use querystring more easy and safely.

 `this.query[key]` change to be always a string.

**Comment by ruimarinho** [comment]
Really nice @fengmk2. Wholeheartedly agree that `this.query[key]` returning an array is really an unsafe default operation. To be honest though, I don't really like the `queryArray` method name. What about `this.query(key)` and `this.query(key, { array: true })`? Also looks like a good candidate for a `Map` :)

Btw, reminds me of https://blogs.dropbox.com/developers/2015/03/json-in-urls/.

**Comment by dougwilson** [comment]
@jonathanong yea, I would like to get a query parsing lib in `pillarjs` at some point. So far I've been riding on `qs`, but it's been meh i.m.o :)

**Comment by fengmk2** [comment]
@ruimarinho current this.query is a getter, I don't want to change it to a method.

How about this.getQuery(key, options) or this.queryValue(key, options)

@dougwilson new qs will release soon ?

**Comment by hotoo** [comment]
What about `this.queryList` or `this.queries` ? I think is not good enough, but better than `this.queryArray`.

**Comment by dead-horse** [comment]
I don't like `this.queryArray` either

**Comment by fengmk2** [comment]
@dead-horse @hotoo @ruimarinho  how about this `this.getQuery(key, {type: array|string|object})`

**Comment by fengmk2** [comment]
Redesign the api again:

Make `this.query[key]` return strict `String` value and add `this.getQuery(key, options)` to return `Array` or `Object` value.

## `this.query[key]` 

equal to  `this.getQuery(key)` and  `this.getQuery(key, {type: 'string'})`

return `String` value

- if key not exists, return `undefined`
- `foo[bar][baz]=foobarbaz` => `{ 'foo[bar][baz]': 'foobarbaz' }`
 - `this.query.foo` return `undefined` 
 - `this.query['foo[bar][baz]']` return `'foobarbaz'`
- `a[]=b&a[]=c` => `{ 'a[]': 'b' }`
 - `this.query.a` return `undefined` 
 - `this.query['a[]']` return `b`

## `this.getQuery(key, {type: array|string|object})`

~~`this.queryArray[key]`~~

- type {String} default is `'string'`

### `this.getQuery(key, {type: 'array'})`

return `Array` value

- if key not exists, return `undefined`
- `foo[bar][baz]=foobarbaz` => `{ 'foo[bar][baz]': [ 'foobarbaz' ] }`
 - `this.getQuery('foo', {type: 'array'})` return `undefined`
 - `this.getQuery('foo[bar][baz]', {type: 'array'})` return `[ 'foobarbaz' ]`
- `a[]=b&a[]=c` => `{ 'a': [ 'b', 'c' ] }`
 - `this.getQuery('a', {type: 'array'})` return `['b', 'c']`
 - `this.getQuery('a[]', {type: 'array'})` return `undefined`
- `a=b` => `{ 'a': [ 'b' ] }`
 - `this.getQuery('a', {type: 'array'})` return `['b']`

### `this.getQuery(key, {type: 'object'})`

return `Object` value

- if key not exists, return `undefined`
- if key exists and value is `non-object`, return `undefined`
- `foo[bar][baz]=foobarbaz` => `this.getQuery('foo', {type: 'object'})` return `{ bar: { baz: 'foobarbaz' } }`
- `a[]=b&a[]=c` => `this.getQuery('a', {type: 'object'})` return `undefined`
- `a=b` => `this.getQuery('a', {type: 'object'})` return `undefined`

**Comment by jonathanong** [comment]
i'm guessing you guys want to make a module first, right? Something like: 

```js
const query = Query(this.querystring);
let value = query.get(key, options);
```

**Comment by fengmk2** [comment]
@jonathanong yep, for the experienced node.js developer he/she can use module way. But most new node.js developer inside my team, I need to make sure they use a same way and don't want them to care  about which version of `querystring` module they need to use.

**Comment by hotoo** [comment]
I think `this.queryObject` and `this.getQuery(key, {type:object})` is awful.

```js
// foo[bar][baz]=foobarbaz => this.queryObject.foo return { bar: { baz: 'foobarbaz' } }
// developer write code following:
var baz = this.queryObject.foo.bar.baz;
// if there not has `foo[bar][baz]` key in querystring, will throw javascript exception.

// developer must write code like following for safe:
var baz;
if (this.queryObject.foo && this.queryObject.foo.bar) {
  baz = this.queryObject.foo.bar.baz;
}
if (typeof baz !== "undefined") {
  // dosomething.
}
```

**Comment by hotoo** [comment]
Just provide `this.query.key` (for String) and `this.queries.key` (for Array) is enough and Turing-complete.

**Comment by hotoo** [comment]
- this.request.query <-- this.query
- this.request.queries <-- this.queries
- this.request.body
- this.request.bodies

**Comment by fengmk2** [comment]
@hotoo your proposal look better :+1:

**Comment by jonathanong** [comment]
let's get this started! https://github.com/pillarjs/qs-strict

**Comment by DenisIzmaylov** [comment]
Could you please implement middle pattern?
To use this package in follow way: 
```
app.use(qs('extended'));
```

**Comment by shannonmpoole** [comment]
:+1: for the middleware pattern. It would allow it to be configured in a koa-router route instead of at the root.

**Comment by itsnotvalid** [comment]
Any plans to upgrade the version for qs?

**Comment by adoyle-h** [comment]
> `request.query[key]` return `String` value

@fengmk2 I think it is unacceptable. I prefer to use `this.getQuery(key, {type: array|string|object})`.

There is a scenario that any middleware could change the `query` for its business. For example, `request.query.one = 1` to add a Number `1` to `query`, and then we will get a String `'1'` when access `request.query.one`;

**Comment by fengmk2** [comment]
@adoyle-h No, `request.query` should be readonly in the whole request process.

**Comment by niftylettuce** [comment]
Closing, feel free to reopen
